
CREATE TABLE `geoip2_location` (
  `geoname_id` int(11) NOT NULL,
  `locale_code` text COLLATE latin1_general_ci NOT NULL,
  `continent_code` text COLLATE latin1_general_ci NOT NULL,
  `continent_name` text COLLATE latin1_general_ci NOT NULL,
  `country_iso_code` text COLLATE latin1_general_ci DEFAULT NULL,
  `country_name` text COLLATE latin1_general_ci DEFAULT NULL,
  `subdivision_1_iso_code` text COLLATE latin1_general_ci DEFAULT NULL,
  `subdivision_1_name` text COLLATE latin1_general_ci DEFAULT NULL,
  `subdivision_2_iso_code` text COLLATE latin1_general_ci DEFAULT NULL,
  `subdivision_2_name` text COLLATE latin1_general_ci DEFAULT NULL,
  `city_name` text COLLATE latin1_general_ci DEFAULT NULL,
  `metro_code` int(11) DEFAULT NULL,
  `time_zone` text COLLATE latin1_general_ci DEFAULT NULL,
  `is_in_european_union` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`geoname_id`,`locale_code`(5))
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;


CREATE TABLE `geoip2_network` (
  `network_start` varbinary(16) NOT NULL,
  `network_end` varbinary(16) NOT NULL,
  `geoname_id` int(11) DEFAULT NULL,
  `registered_country_geoname_id` int(11) DEFAULT NULL,
  `represented_country_geoname_id` int(11) DEFAULT NULL,
  `is_anonymous_proxy` tinyint(1) DEFAULT NULL,
  `is_satellite_provider` tinyint(1) DEFAULT NULL,
  `postal_code` text COLLATE latin1_general_ci DEFAULT NULL,
  `latitude` float DEFAULT NULL,
  `longitude` float DEFAULT NULL,
  `accuracy_radius` int(11) DEFAULT NULL,
  KEY `network_start` (`network_start`),
  KEY `network_end` (`network_end`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;


CREATE TABLE `redirects` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `uri` text NOT NULL,
  `destination` text NOT NULL,
  `hits` int(11) NOT NULL DEFAULT 0,
  `created` datetime NOT NULL DEFAULT current_timestamp(),
  `updated` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `visit_params` (
  `id` bigint(11) unsigned NOT NULL AUTO_INCREMENT,
  `visit_id` bigint(11) NOT NULL,
  `param_key` varchar(255) NOT NULL DEFAULT '',
  `param_value` varchar(1024) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `visit_id` (`visit_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



CREATE TABLE `visits` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `redirect_id` int(11) DEFAULT NULL,
  `uri` text COLLATE latin1_general_ci DEFAULT NULL,
  `ip` mediumtext COLLATE latin1_general_ci DEFAULT NULL,
  `lat` decimal(10,7) DEFAULT NULL,
  `lng` decimal(10,7) DEFAULT NULL,
  `city` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `region` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `country` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `browser` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `browser_type` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `browser_bits` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `browser_maker` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `browser_modus` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `version` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `majorver` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `minorver` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `platform` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `platform_version` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `platform_description` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `platform_bits` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `platform_maker` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `alpha` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `beta` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `win16` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `win32` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `win64` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `frames` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `iframes` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `tables` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `cookies` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `backgroundsounds` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `javascript` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `vbscript` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `javaapplets` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `activexcontrols` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `ismobiledevice` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `istablet` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `issyndicationreader` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `crawler` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `isfake` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `isanonymized` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `ismodified` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `cssversion` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `aolversion` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `device_name` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `device_maker` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `device_type` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `device_pointing_method` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `device_code_name` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `device_brand_name` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `renderingengine_name` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `renderingengine_version` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `renderingengine_description` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  `renderingengine_maker` varchar(255) COLLATE latin1_general_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `city` (`city`),
  KEY `region` (`region`),
  KEY `country` (`country`),
  KEY `browser` (`browser`),
  KEY `browser_type` (`browser_type`),
  KEY `browser_bits` (`browser_bits`),
  KEY `browser_maker` (`browser_maker`),
  KEY `browser_modus` (`browser_modus`),
  KEY `version` (`version`),
  KEY `majorver` (`majorver`),
  KEY `minorver` (`minorver`),
  KEY `platform` (`platform`),
  KEY `platform_version` (`platform_version`),
  KEY `platform_description` (`platform_description`),
  KEY `platform_bits` (`platform_bits`),
  KEY `platform_maker` (`platform_maker`),
  KEY `alpha` (`alpha`),
  KEY `beta` (`beta`),
  KEY `win16` (`win16`),
  KEY `win32` (`win32`),
  KEY `win64` (`win64`),
  KEY `frames` (`frames`),
  KEY `iframes` (`iframes`),
  KEY `tables` (`tables`),
  KEY `cookies` (`cookies`),
  KEY `backgroundsounds` (`backgroundsounds`),
  KEY `javascript` (`javascript`),
  KEY `vbscript` (`vbscript`),
  KEY `javaapplets` (`javaapplets`),
  KEY `activexcontrols` (`activexcontrols`),
  KEY `ismobiledevice` (`ismobiledevice`),
  KEY `istablet` (`istablet`),
  KEY `issyndicationreader` (`issyndicationreader`),
  KEY `crawler` (`crawler`),
  KEY `isfake` (`isfake`),
  KEY `isanonymized` (`isanonymized`),
  KEY `ismodified` (`ismodified`),
  KEY `cssversion` (`cssversion`),
  KEY `aolversion` (`aolversion`),
  KEY `device_name` (`device_name`),
  KEY `device_maker` (`device_maker`),
  KEY `device_type` (`device_type`),
  KEY `device_pointing_method` (`device_pointing_method`),
  KEY `device_code_name` (`device_code_name`),
  KEY `device_brand_name` (`device_brand_name`),
  KEY `renderingengine_name` (`renderingengine_name`),
  KEY `renderingengine_version` (`renderingengine_version`),
  KEY `renderingengine_description` (`renderingengine_description`),
  KEY `renderingengine_maker` (`renderingengine_maker`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
